[project]
name = "diploma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexey Krasnikov", email = "creeper.kr@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "catboost>=1.2.10",
    "imbalanced-learn>=0.14.2",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "xgboost>=3.4.1",
]

[project.scripts]
diploma = "diploma:main"

[tool.uv]
package = false
